# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    secure: Uw8EZ29j9Xl3VjI4ekFej6ml+aCSGqmF/Hipb0p3qzMKKSR+W168g1bE/ocF0XMnglyEX1nkGYGDLtsxewhbajoaeiDGXrqwCTqJrKsd0B5DExNRTREsBUEJkWjQQ6ZJfiXeK7pfKJBlnoBXnBJM551SBI48dndNbRQcsGUHqGKAJl2mlP4hq07kMviFR3YzQzU1mneem8AtCqiFEqsre4A6PYftzl2sAT+Bf/jImRky00bFtS+K6tXQuldz1EO0ElGYFsGBbp1zEuj5Jc2EBbfTF1D8NkwOsJdjWKKvE3D9XQFgyr52lu155xHpbKB9tq2lij7L/CWHPCcBw1+IdWCJxEiMEEFxQ8koX+d4q6uRqgMVz1VKNg66Axlikv1SC7eC+UgNh+z4unZR+ikqvX0HA5GZ1Nrz2lFBNWEZ5Go2RomDwU2Q8XXdQ4GlS5t3hYA5QSnw50DA/L9tqkxTlO3uQh3ePFVLsEWxZw+4N3HAMGJvudypwxlMYht4Qtmkpca/QIVgk6wrnH9Nj2XHm7Z9IHLzmz5OFEHt9jmdaOAV4m56sjCmjpBgKcd8vLFYqIk612cizdNWUsFALcQk0u+IwzU5VVbXAzD/vvvuWMnz2aFB77Ok0Tofso5y1PgFOWaB7y3KvhuXMLQCFcKRf3DPD2ZQQ5ukPI2dQBTstJc=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: LL/zuavI74CfXqoDgQ8mCl2s+4Gg/YGDyR+iS9/dHnWLRxeCLHf7GJ88X6ErkE7+1NJnx/NDkjIjTSjnWlpFUhNW2iSDHv0qI3vLKAJY7LslE6Bro3rkDu9LwiBv+WK7Np32hbGAH2WgSPWLkIHEOM14JfBMhVE0C0DL6+wSWuDhckPl7O9gCH9XyYMuBOaFTYq6J54CfWTxh25fdh+gbT7nakcDxVZwrmcbEdNUB+a7RSbRVFi24Js0EWQT5L9zE/jbqqRgLpsOZ9qfTGiTUdk9QVaAHjmKKXsIaWilkw6hZOagk7hB4tj/1ClBfvvNG4wZNYY1Uz4C7cWkPbaul7d/MjzuN//5F+VONKFRngLWI5UA8bdB4qvlGt+eKaYe41Ms45C23ZeYFSwydXpWG3EUIho3qPGiCqOsL+IFOdKdDDouF5R6rM4IHwQjFeb4dnon7Uz65GFQFJsVA3zft5DmWaRZqNcf7g2TGgHhCKZbSPqJiaG977BrvVjvlfa0GirXjtJ6HCA14g6LQqkLxLU61vJ6lpTEi0tFQJw44vNJCMSQiYo1i0ZaZrnnyy0F/g9Au9DR7lhY1SDSuNZyA5X8RA1+gVLDfulmeHSftYf6a8CcCT19gX67o/eQxKp6/el/80yI8eHsOVlp5oFPVkmelT7nHH4lRLKo0LiP+nE=
