# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    secure: Uw8EZ29j9Xl3VjI4ekFej6ml+aCSGqmF/Hipb0p3qzMKKSR+W168g1bE/ocF0XMnglyEX1nkGYGDLtsxewhbajoaeiDGXrqwCTqJrKsd0B5DExNRTREsBUEJkWjQQ6ZJfiXeK7pfKJBlnoBXnBJM551SBI48dndNbRQcsGUHqGKAJl2mlP4hq07kMviFR3YzQzU1mneem8AtCqiFEqsre4A6PYftzl2sAT+Bf/jImRky00bFtS+K6tXQuldz1EO0ElGYFsGBbp1zEuj5Jc2EBbfTF1D8NkwOsJdjWKKvE3D9XQFgyr52lu155xHpbKB9tq2lij7L/CWHPCcBw1+IdWCJxEiMEEFxQ8koX+d4q6uRqgMVz1VKNg66Axlikv1SC7eC+UgNh+z4unZR+ikqvX0HA5GZ1Nrz2lFBNWEZ5Go2RomDwU2Q8XXdQ4GlS5t3hYA5QSnw50DA/L9tqkxTlO3uQh3ePFVLsEWxZw+4N3HAMGJvudypwxlMYht4Qtmkpca/QIVgk6wrnH9Nj2XHm7Z9IHLzmz5OFEHt9jmdaOAV4m56sjCmjpBgKcd8vLFYqIk612cizdNWUsFALcQk0u+IwzU5VVbXAzD/vvvuWMnz2aFB77Ok0Tofso5y1PgFOWaB7y3KvhuXMLQCFcKRf3DPD2ZQQ5ukPI2dQBTstJc=

# Npm publish options
before_deploy:
  - npm install coffee-script --global
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: EgwMH+4evvZaGOiALLRsrW7BvxdKCQIpT0n9N1wQlp1uAKTfWAGkgax/lyWxNr2EZKhLSMhApaYXte5ybRTnzG3buFc7oHumJ9AiZrW1prv4VNmaydssCCwTqJgQjStKOf6IgByiBOpRRtz61YwnE1+BhYqUGV7L8KSwzYW77trx1aT6fHXz7uuluUSTETSShKt93G3JRseiVB0tEWqawP/B6khJiBCH7WmAl+CUsfwKsKg5/6Zj+guBUZx/JVU+msouGi2/pw/gcK+FhRtOUaVIKk3JmRfgd+cG+0A8wquh2ggPHdnhR0sRr4iAOY3eYvWxuh//UT2E4pD0PQeyCr6JG2lGrkgAZ1cpwgrG1b8yMacrPtXPskBntNVU0QY1JsByzZaBJvOXbZ8dpSdMLrFfoM+haKL+S5bM2PwuZ/Q50fRGfGCPj0LFQVPicRwjVgLRSE4VnwdR48Fhy38wO/Y0Aj6p/KpWrt20vWJ7q4NKjUVeb9hUocCohg1izF3NfobtFYQ/aQjC2R1hXV4IPqPFkJnHFDsZrRJYrXFK/d3f4AYSOgWVU1nteSNLXBUr7kdk446koG7hmsBnwq/tInfXhdYwFIuIYWp0av3f0V256nYYeG0iCWL1bVhTzqdR837m8I+Gwd/VjH08x5QuBQxzBv9NlaLt0IYQTFggAnA=
